In [1]:
import numpy as np

In [4]:
M = np.array([[1,2,3,4], [5,6,7,8],[8,10,11,12]]) #Matriz é um array de mais de uma dimensão

In [6]:
M

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 8, 10, 11, 12]])

In [7]:
type(M)

numpy.ndarray

In [9]:
M2 = np.matrix([[1,2,3,4], [5,6,7,8],[8,10,11,12]])

In [11]:
type(M2)

numpy.matrix

In [13]:
M2

matrix([[ 1,  2,  3,  4],
        [ 5,  6,  7,  8],
        [ 8, 10, 11, 12]])

In [19]:
M2[0,:]

matrix([[1, 2, 3, 4]])

In [20]:
M2[:,0]

matrix([[1],
        [5],
        [8]])

In [22]:
M2[0,0]

1