In [35]:
import os
import numpy as np
import pandas as pd
import pickle
from sklearn.model_selection import train_test_split
from sklearn.metrics import accuracy_score, confusion_matrix, classification_report
from sklearn.model_selection import KFold
from sklearn.model_selection import cross_val_score
from sklearn.linear_model import LogisticRegression

In [36]:
previsores_file = open(f'{os.getcwd()}\\Tratamento e Pre-Processamento\\Dados\\heart_previsores_ecd_esc.pkl', 'rb')
previsores = pickle.load(previsores_file)
previsores_file.close()
previsores

alvo_file = open(f'{os.getcwd()}\\Tratamento e Pre-Processamento\\Dados\\heart_alvo.pkl', 'rb')
alvo = pickle.load(alvo_file)
alvo_file.close()

In [37]:
previsores_treino, previsores_teste, alvo_treino, alvo_teste = train_test_split(previsores, alvo, test_size = 0.3, random_state = 0)

In [38]:
logistica = LogisticRegression(random_state=1, max_iter = 600, penalty = 'l2', tol = 0.0001, C = 1, solver = 'lbfgs')
logistica.fit(previsores_treino, alvo_treino)

LogisticRegression(C=1, max_iter=600, random_state=1)

In [39]:
logistica.intercept_

array([0.27651292])

In [40]:
logistica.coef_

array([[-0.31429216,  0.31429216,  0.51145815, -0.41291678, -0.17911607,
        -0.08746201,  0.05928251, -0.00197428, -0.05806686, -0.21969455,
         0.21969455, -0.01971658,  0.60969113, -0.6055519 ,  0.1808035 ,
        -0.00090394,  0.18908439,  0.43510469, -0.22824874,  0.29941155]])

In [41]:
previsoes_logistica = logistica.predict(previsores_teste)

In [42]:
print('Acurácia %.2f%%' % (accuracy_score(alvo_teste, previsoes_logistica) * 100))

Acurácia 86.23%


In [43]:
confusion_matrix(alvo_teste, previsoes_logistica)

array([[102,  19],
       [ 19, 136]], dtype=int64)

In [44]:
print(classification_report(alvo_teste, previsoes_logistica))

              precision    recall  f1-score   support

           0       0.84      0.84      0.84       121
           1       0.88      0.88      0.88       155

    accuracy                           0.86       276
   macro avg       0.86      0.86      0.86       276
weighted avg       0.86      0.86      0.86       276



In [45]:
previsoes_treino = logistica.predict(previsores_treino)

In [46]:
accuracy_score(alvo_treino, previsoes_treino)

0.858034321372855

In [47]:
confusion_matrix(alvo_treino, previsoes_treino)

array([[237,  52],
       [ 39, 313]], dtype=int64)

In [48]:
#Validação Cruzada

In [49]:
kfold = KFold(n_splits = 30, shuffle=True, random_state = 5)

In [50]:
modelo = LogisticRegression(random_state=1, max_iter = 800, penalty = 'l2', tol = 0.0001, C = 2, solver = 'lbfgs')
resultado = cross_val_score(modelo, previsores, alvo, cv = kfold)

In [51]:
print('Acuracia Média: %.2f%%' % (resultado.mean() * 100))

Acuracia Média: 85.83%
