In [1]:
import numpy as np
import pandas as pd
import pickle
from sklearn.preprocessing import StandardScaler
from sklearn.preprocessing import LabelEncoder
from sklearn.preprocessing import OneHotEncoder
from sklearn.compose import ColumnTransformer
import os

In [2]:
df = pd.read_csv(f'{os.getcwd()}\\Dados\\heart_tratado.csv', sep=';', encoding='utf-8')

In [3]:
df.head()

Age Sex ChestPainType  RestingBP  Cholesterol  FastingBS RestingECG  MaxHR  \
0   40   M           ATA        140        289.0          0     Normal    172   
1   49   F           NAP        160        180.0          0     Normal    156   
2   37   M           ATA        130        283.0          0         ST     98   
3   48   F           ASY        138        214.0          0     Normal    108   
4   54   M           NAP        150        195.0          0     Normal    122   

  ExerciseAngina  Oldpeak ST_Slope  HeartDisease  
0              N      0.0       Up             0  
1              N      1.0     Flat             1  
2              N      0.0       Up             0  
3              Y      1.5     Flat             1  
4              N      0.0       Up             0

In [4]:
#Pegando as colunas dos dados previsores
previsores = df.iloc[:,0:11].values
previsores

array([[40, 'M', 'ATA', ..., 'N', 0.0, 'Up'],
       [49, 'F', 'NAP', ..., 'N', 1.0, 'Flat'],
       [37, 'M', 'ATA', ..., 'N', 0.0, 'Up'],
       ...,
       [57, 'M', 'ASY', ..., 'Y', 1.2, 'Flat'],
       [57, 'F', 'ATA', ..., 'N', 0.0, 'Flat'],
       [38, 'M', 'NAP', ..., 'N', 0.0, 'Up']], dtype=object)

In [5]:
#Transformando categóricas nominais em categórica ordinais
previsores[:,1] = LabelEncoder().fit_transform(previsores[:,1])
previsores[:,2] = LabelEncoder().fit_transform(previsores[:,2])
previsores[:,6] = LabelEncoder().fit_transform(previsores[:,6])
previsores[:,8] = LabelEncoder().fit_transform(previsores[:,8])
previsores[:,10] = LabelEncoder().fit_transform(previsores[:,10])
previsores

array([[40, 1, 1, ..., 0, 0.0, 2],
       [49, 0, 2, ..., 0, 1.0, 1],
       [37, 1, 1, ..., 0, 0.0, 2],
       ...,
       [57, 1, 0, ..., 1, 1.2, 1],
       [57, 0, 1, ..., 0, 0.0, 1],
       [38, 1, 2, ..., 0, 0.0, 2]], dtype=object)

In [6]:
previsores_file = open(f'{os.getcwd()}\\Dados\\heart_previsores_le.pkl', 'wb')
pickle.dump(previsores, previsores_file)
previsores_file.close()
previsores.shape

(917, 11)

In [7]:
#Transforma cada variável categórica em uma coluna. As colunas recebem valor 0 ou 1 (a ideia é retirar 'pesos' de variáveis categóricas)
previsores_encoded = ColumnTransformer(transformers=[('OneHot', OneHotEncoder(), [1,2,6,8,10])], remainder='passthrough').fit_transform(previsores)
previsores_encoded

array([[0.0, 1.0, 0.0, ..., 0, 172, 0.0],
       [1.0, 0.0, 0.0, ..., 0, 156, 1.0],
       [0.0, 1.0, 0.0, ..., 0, 98, 0.0],
       ...,
       [0.0, 1.0, 1.0, ..., 0, 115, 1.2],
       [1.0, 0.0, 0.0, ..., 0, 174, 0.0],
       [0.0, 1.0, 0.0, ..., 0, 173, 0.0]], dtype=object)

In [8]:
previsores_encoded_df = pd.DataFrame(previsores_encoded)
previsores_encoded_df.tail()

0    1    2    3    4    5    6    7    8    9    10   11   12   13  14  \
912  0.0  1.0  0.0  0.0  0.0  1.0  0.0  1.0  0.0  1.0  0.0  0.0  1.0  0.0  45   
913  0.0  1.0  1.0  0.0  0.0  0.0  0.0  1.0  0.0  1.0  0.0  0.0  1.0  0.0  68   
914  0.0  1.0  1.0  0.0  0.0  0.0  0.0  1.0  0.0  0.0  1.0  0.0  1.0  0.0  57   
915  1.0  0.0  0.0  1.0  0.0  0.0  1.0  0.0  0.0  1.0  0.0  0.0  1.0  0.0  57   
916  0.0  1.0  0.0  0.0  1.0  0.0  0.0  1.0  0.0  1.0  0.0  0.0  0.0  1.0  38   

      15     16 17   18   19  
912  110  264.0  0  132  1.2  
913  144  193.0  1  141  3.4  
914  130  131.0  0  115  1.2  
915  130  236.0  0  174  0.0  
916  138  175.0  0  173  0.0

In [13]:
#Colocando as variáveis em uma escala padrão
previsores_encoded_esc = StandardScaler().fit_transform(previsores_encoded)

In [10]:
previsores_ecd_esc_file = open(f'{os.getcwd()}\\Dados\\heart_previsores_ecd_esc.pkl', 'wb')
pickle.dump(previsores_encoded_esc, previsores_ecd_esc_file)
previsores_ecd_esc_file.close()

In [11]:
previsores_ecd_file = open(f'{os.getcwd()}\\Dados\\heart_previsores_ecd.pkl', 'wb')
pickle.dump(previsores_encoded, previsores_ecd_file)
previsores_ecd_file.close()