In [2]:
import pandas as pd
import numpy as np

In [3]:
series = pd.Series([7, 4, 2, np.nan, 6, 9])

In [4]:
series


0    7.0
1    4.0
2    2.0
3    NaN
4    6.0
5    9.0
dtype: float64

In [5]:
type(series)

pandas.core.series.Series

In [6]:
datas = pd.date_range('20180101', periods = 6)
datas

DatetimeIndex(['2018-01-01', '2018-01-02', '2018-01-03', '2018-01-04',
               '2018-01-05', '2018-01-06'],
              dtype='datetime64[ns]', freq='D')

In [7]:
type(datas)

pandas.core.indexes.datetimes.DatetimeIndex

In [8]:
df = pd.DataFrame(np.random.randn(6,4), index = datas, columns = list('ABCD'))
df

A         B         C         D
2018-01-01 -0.159353  1.396486 -0.917865 -0.280749
2018-01-02 -1.569425  1.057229  0.418418  1.224589
2018-01-03  0.837165 -1.078183  1.092963 -1.168143
2018-01-04  0.940247  0.664942  0.911802 -0.560578
2018-01-05 -0.570228 -1.434117  1.510433 -0.126334
2018-01-06 -1.437102  0.537412  0.234171  0.937718

In [9]:
df2 = pd.DataFrame(np.random.randn(6,4), index = datas, columns = ['Carros', 'Países', 'Pessoas', 'Python'])
df2

Carros    Países   Pessoas    Python
2018-01-01  1.533359  0.955952  1.641350 -1.025881
2018-01-02 -0.066065  0.850607  0.884515  1.903209
2018-01-03 -0.957851  2.287725  1.315235 -1.946983
2018-01-04 -0.904426 -0.129325  0.453971  0.641240
2018-01-05 -0.339092  1.573482 -0.989851  2.336673
2018-01-06 -0.562245  0.108397 -1.376970  2.325306

In [10]:
type(df)

pandas.core.frame.DataFrame

In [11]:
df3 = pd.DataFrame({'A': 7,
                      'B': pd.Timestamp('20190101'),
                      'C': pd.Series(1, index = list(range(4)), dtype = 'float32'),
                      'D': np.array([3] * 4, dtype = 'int32'),
                      'E': pd.Categorical(["test", "train", "test", "train"]),
                      'F': 'Python'})

df3                        

A          B    C  D      E       F
0  7 2019-01-01  1.0  3   test  Python
1  7 2019-01-01  1.0  3  train  Python
2  7 2019-01-01  1.0  3   test  Python
3  7 2019-01-01  1.0  3  train  Python

In [12]:
df3.dtypes

A             int64
B    datetime64[ns]
C           float32
D             int32
E          category
F            object
dtype: object

In [13]:
df.head(3)

A         B         C         D
2018-01-01 -0.159353  1.396486 -0.917865 -0.280749
2018-01-02 -1.569425  1.057229  0.418418  1.224589
2018-01-03  0.837165 -1.078183  1.092963 -1.168143

In [14]:
df.tail(3)

A         B         C         D
2018-01-04  0.940247  0.664942  0.911802 -0.560578
2018-01-05 -0.570228 -1.434117  1.510433 -0.126334
2018-01-06 -1.437102  0.537412  0.234171  0.937718

In [15]:
df.index

DatetimeIndex(['2018-01-01', '2018-01-02', '2018-01-03', '2018-01-04',
               '2018-01-05', '2018-01-06'],
              dtype='datetime64[ns]', freq='D')

In [16]:
df.columns

Index(['A', 'B', 'C', 'D'], dtype='object')

In [17]:
df.to_numpy()

array([[-0.15935315,  1.39648639, -0.91786549, -0.28074861],
       [-1.56942522,  1.05722926,  0.41841789,  1.22458889],
       [ 0.83716531, -1.07818293,  1.09296288, -1.16814268],
       [ 0.94024711,  0.66494229,  0.91180247, -0.56057818],
       [-0.57022826, -1.43411724,  1.51043292, -0.12633417],
       [-1.43710245,  0.53741182,  0.2341706 ,  0.93771849]])

In [18]:
df.T

2018-01-01  2018-01-02  2018-01-03  2018-01-04  2018-01-05  2018-01-06
A   -0.159353   -1.569425    0.837165    0.940247   -0.570228   -1.437102
B    1.396486    1.057229   -1.078183    0.664942   -1.434117    0.537412
C   -0.917865    0.418418    1.092963    0.911802    1.510433    0.234171
D   -0.280749    1.224589   -1.168143   -0.560578   -0.126334    0.937718

In [20]:
df.shape

(6, 4)

In [23]:
df.size

24

In [25]:
df.values #cada dimensão do array é uma coluna

array([[-0.15935315,  1.39648639, -0.91786549, -0.28074861],
       [-1.56942522,  1.05722926,  0.41841789,  1.22458889],
       [ 0.83716531, -1.07818293,  1.09296288, -1.16814268],
       [ 0.94024711,  0.66494229,  0.91180247, -0.56057818],
       [-0.57022826, -1.43411724,  1.51043292, -0.12633417],
       [-1.43710245,  0.53741182,  0.2341706 ,  0.93771849]])

In [29]:
df.values.reshape((2,12))

array([[-0.15935315,  1.39648639, -0.91786549, -0.28074861, -1.56942522,
         1.05722926,  0.41841789,  1.22458889,  0.83716531, -1.07818293,
         1.09296288, -1.16814268],
       [ 0.94024711,  0.66494229,  0.91180247, -0.56057818, -0.57022826,
        -1.43411724,  1.51043292, -0.12633417, -1.43710245,  0.53741182,
         0.2341706 ,  0.93771849]])